export default {
      "AK": [],
      "ME": ["NH"],
      "VT": ["NH", "MA", "NY"],
      "NH": ["VT", "MA", "ME"],
      "WA": ["ID", "OR"],
      "MT": ["ID", "WY", "ND", "SD"],
      "ND": ["SD", "MT", "MN"],
      "MN": ["ND", "SD", "IA", "WI"],
      "WI": ["MN", "IA", "IL", "MI"],
      "MI": ["WI", "OH", "IN"],
      "NY": ["PA", "VT", "MA", "CT", "NJ"],
      "MA": ["NY", "NH", "VT", "CT", "RI"],
      "RI": ["MA", "CT"],
      "ID": ["WA", "OR", "MT", "WY", "NV", "UT"],
      "WY": ["MT", "ID", "UT", "CO", "NE", "SD"],
      "SD": ["ND", "WY", "MT", "NE", "IA", "MN"],
      "IA": ["MN", "NE","SD", "MO", "WI", "IL"],
      "IL": ["WI", "IA", "MO", "TN", "IN", "KY"],
      "IN": ["MI", "IL", "OH", "KY"],
      "OH": ["OH", "IN", "PA", "KY", "WV"],
      "PA": ["NY", "OH", "NJ", "DE", "MD", "WV"],
      "NJ": ["NY", "PA", "DE"],
      "CT": ["NY", "MA", "RI"],
      "OR": ["WA", "ID", "CA", "NV"],
      "NV": ["CA", "UT", "NM", "ID", "OR"],
      "CO": ["UT", "WY", "NE", "KA", "OK"],
      "NE": ["WY", "CO", "KA", "IA", "MO", "SD"],
      "MO": ["KA", "IA", "IL","TN", "AR"],
      "KY": ["IL", "ID", "TN", "MO", "WV", "VA", "NC"],
      "WV": ["OH", "KY", "VA", "PA", "MD"],
      "VA": ["WV", "NC", "TN", "MD"],
      "MD": ["PA", "WV", "VA", "DE"],
      "DE": ["NJ", "PA", "MD"],
      "CA": ["OR", "NV", "AZ"],
      "UT": ["NV", "ID", "UT", "AZ", "CO", "WY"],
      "NM": ["AZ", "TX", "CO", "OK"],
      "KS": ["OK", "CO", "MO", "NE"],
      "AR": ["MO", "OK", "MS", "TN", "TX", "LA"],
      "TN": ["AR", "MS", "AL", "GA", "KY", "NC"],
      "NC": ["VA", "SC", "TN", "GA"],
      "SC": ["GA", "NC"],
      "DC": [],
      "AZ": ["CA", "NM", "UT"],
      "OK": ["NM", "KS", "CO", "TX", "AK", "MO"],
      "LA": ["TX", "AR", "MS"],
      "MS": ["LA", "AL", "TN", "AR"],
      "AL": ["TN", "MS", "GA", "FL"],
      "GA": ["AL", "FL", "SC", "TN"],
      "HI": [],
      "TX": ["OK", "AR", "LA", "NM"],
      "FL": ["AL", "GA"],
  }
